FROM node:lts-alpine

LABEL description="Runs the database migrations then exits"

WORKDIR /code
EXPOSE 3500

ENV NODE_ENV="production" \
    AWS_REGION="ap-southeast-2" \
    DB_CONNECTION_STRING=""

# Install production dependencies
RUN yarn --prod

# Then copy code in
COPY ./dist/ /code


CMD node /code/index.js
