FROM node:lts-alpine

LABEL description="Runs the database migrations then exits"

WORKDIR /

ENV NODE_ENV="production" \
    AWS_REGION="ap-southeast-2"

# Install production dependencies

COPY src/ /src
COPY package.json package-lock.json webpack.config.js tsconfig.json /

RUN npm install
RUN npm run build

WORKDIR /dist


